# MoveIt uses this to know which controllers to use for execution
moveit_simple_controller_manager:
  controller_names:
    - scaled_joint_trajectory_controller  # <-- CHANGE 1: Use running controller name
    - hande_gripper_controller

  # Configuration for the ARM
  scaled_joint_trajectory_controller:  # <-- CHANGE 2: Rename the block
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  # Configuration for the GRIPPER (Added this)
  hande_gripper_controller:
    # The action namespace for GripperActionController is usually 'gripper_cmd'
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - robotiq_hande_left_finger_joint
