moveit_simple_controller_manager:
  controller_names:
    - scaled_joint_trajectory_controller
    - hande_gripper_controller

  scaled_joint_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    # ADDED: Stops the "Goal Rejected" error if the sim robot is slightly off-position
    allowed_start_tolerance: 0.1 

  hande_gripper_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - robotiq_hande_left_finger_joint
    allowed_start_tolerance: 0.1

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  execution_duration_monitoring: false