planning_plugin: ompl_interface/OMPLPlanner

planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
  RRTkConfigDefault:
    type: geometric::RRT
    range: 0.0
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0

ur_manipulator:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTkConfigDefault
    - RRTstarkConfigDefault

gripper:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault

request_adapters: >-
  default_planner_request_adapters/ResolveConstraintFrames
  default_planner_request_adapters/ValidateWorkspaceBounds
  default_planner_request_adapters/CheckStartStateBounds
  default_planner_request_adapters/CheckStartStateCollision
  default_planner_request_adapters/AddTimeOptimalParameterization