apf_servo_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity